---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: webapp
spec:
  replicas: 1  # Initial number of replicas
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"  # Request 256 MiB of memory
            cpu: "250m"      # Request 0.25 CPU core
          limits:
            memory: "512Mi"  # Request 512 MiB of memory
            cpu: "500m"      # Request 0.5 CPU core

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: nginx-web
  ports:
    - port: 8080        # Port exposed within the cluster
      targetPort: 80    # Port on the pods
      # nodePort: 30080   # Optional: Specify a specific NodePort (will be auto-assigned if omitted)
